name: React CI

on:
  push:
    branches:
      - "master"

jobs:
 install-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.8]

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm test
      
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: samanwanich/numer
          tag: frontend
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v1
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: samanwanich/numer
          tag: backend
          dockerfile: server/Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
