name: React CI

on:
  push:
    branches:
      - "master"

jobs:
 install-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.8]

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm test